In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/layoffs.csv")

In [2]:
df.head()

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,SentinelOne,SF Bay Area,230.0,5/29/2026,0.08,Security,https://www.calcalistech.com/ctechnews/article...,Post-IPO,696.0,United States,5/29/2026
1,Rapyd,"Tel Aviv, Non-U.S.",NaN,5/28/2026,NaN,Finance,https://www.calcalistech.com/ctechnews/article...,Unknown,770.0,Israel,5/28/2026
2,NetApp,SF Bay Area,77.0,5/27/2026,NaN,Data,https://hoodline.com/2026/05/san-jose-mainstay...,Post-IPO,NaN,United States,5/28/2026
3,Lightricks,"Jerusalem, Non-U.S.",NaN,5/27/2026,NaN,Consumer,https://en.globes.co.il/en/article-lightricks-...,Series D,335.0,Israel,5/28/2026
4,Webflow,SF Bay Area,NaN,5/27/2026,NaN,Marketing,https://webflow.com/blog/evolving-webflow-for-...,Series C,335.0,United States,5/27/2026

In [3]:
df.shape

(4428, 11)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4428 entries, 0 to 4427
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4428 non-null   str
 1   location             4427 non-null   str
 2   total_laid_off       2900 non-null   float64
 3   date                 4428 non-null   str
 4   percentage_laid_off  2787 non-null   float64
 5   industry             4426 non-null   str
 6   source               4425 non-null   str
 7   stage                4423 non-null   str
 8   funds_raised         3916 non-null   float64
 9   country              4426 non-null   str
 10  date_added           4428 non-null   str
dtypes: float64(3), str(8)
memory usage: 380.7 KB

In [6]:
df_clean = df.copy()

In [7]:
df_clean.duplicated().sum()

np.int64(0)

In [8]:
missing = df_clean.isnull().sum()

missing

company                   0
location                  1
total_laid_off         1528
date                      0
percentage_laid_off    1641
industry                  2
source                    3
stage                     5
funds_raised            512
country                   2
date_added                0
dtype: int64

In [9]:
missing_percent = (df_clean.isnull().sum() / len(df_clean)) * 100

missing_percent.sort_values(ascending=False)

percentage_laid_off    37.059621
total_laid_off         34.507678
funds_raised           11.562782
stage                   0.112918
source                  0.067751
country                 0.045167
industry                0.045167
location                0.022584
company                 0.000000
date                    0.000000
date_added              0.000000
dtype: float64

In [10]:
df_clean[
    df_clean["total_laid_off"].isna() &
    df_clean["percentage_laid_off"].isna()
].shape

(723, 11)

In [11]:
df_clean[
    df_clean["total_laid_off"].isna() &
    df_clean["percentage_laid_off"].isna()
].head()

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
1,Rapyd,"Tel Aviv, Non-U.S.",NaN,5/28/2026,NaN,Finance,https://www.calcalistech.com/ctechnews/article...,Unknown,770.0,Israel,5/28/2026
3,Lightricks,"Jerusalem, Non-U.S.",NaN,5/27/2026,NaN,Consumer,https://en.globes.co.il/en/article-lightricks-...,Series D,335.0,Israel,5/28/2026
4,Webflow,SF Bay Area,NaN,5/27/2026,NaN,Marketing,https://webflow.com/blog/evolving-webflow-for-...,Series C,335.0,United States,5/27/2026
16,Gambling.com Group,"Dublin, Non-U.S.",NaN,5/14/2026,NaN,Other,https://finance.yahoo.com/markets/stocks/artic...,Post-IPO,276.0,Ireland,5/15/2026
24,GitLab,SF Bay Area,NaN,5/11/2026,NaN,Product,https://www.bloomberg.com/news/articles/2026-0...,Post-IPO,413.0,United States,5/11/2026

In [12]:
df_clean[df_clean["location"].isna()]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
1317,Product Hunt,NaN,NaN,10/9/2023,0.6,Consumer,https://techcrunch.com/2023/10/19/product-hunt...,Acquired,NaN,United States,10/15/2023

In [14]:
df_clean[df_clean["industry"].isna()]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
294,Eyeo,"Cologne, Non-U.S.",NaN,7/28/2025,0.40,NaN,https://www.adexchanger.com/privacy/eyeo-names...,Unknown,NaN,Germany,7/30/2025
1359,Appsmith,SF Bay Area,35.0,9/22/2023,0.25,NaN,https://inc42.com/buzz/exclusive-insight-partn...,Series B,51.0,United States,9/24/2023

In [15]:
df_clean[df_clean["country"].isna()]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
1351,Fit Analytics,"Berlin, Non-U.S.",NaN,9/28/2023,1.0,Retail,https://www.businessinsider.de/gruenderszene/t...,Acquired,NaN,NaN,9/29/2023
1636,Ludia,"Montreal, Non-U.S.",55.0,6/28/2023,NaN,Consumer,https://mobilegamer.biz/up-to-55-staff-laid-of...,Acquired,1.0,NaN,6/30/2023

In [16]:
df_clean["location"] = df_clean["location"].fillna("Unknown")

In [17]:
df_clean[df_clean["company"] == "Eyeo"]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
294,Eyeo,"Cologne, Non-U.S.",NaN,7/28/2025,0.4,NaN,https://www.adexchanger.com/privacy/eyeo-names...,Unknown,NaN,Germany,7/30/2025

In [18]:
df_clean[df_clean["company"] == "Appsmith"]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
1359,Appsmith,SF Bay Area,35.0,9/22/2023,0.25,NaN,https://inc42.com/buzz/exclusive-insight-partn...,Series B,51.0,United States,9/24/2023

In [19]:
df_clean[df_clean["company"] == "Fit Analytics"]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
1351,Fit Analytics,"Berlin, Non-U.S.",NaN,9/28/2023,1.0,Retail,https://www.businessinsider.de/gruenderszene/t...,Acquired,NaN,NaN,9/29/2023

In [20]:
df_clean[df_clean["company"] == "Ludia"]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
1636,Ludia,"Montreal, Non-U.S.",55.0,6/28/2023,NaN,Consumer,https://mobilegamer.biz/up-to-55-staff-laid-of...,Acquired,1.0,NaN,6/30/2023

In [21]:
df_clean.loc[df_clean["company"] == "Fit Analytics", "country"] = "Germany"

df_clean.loc[df_clean["company"] == "Ludia", "country"] = "Canada"

In [22]:
df_clean["industry"] = df_clean["industry"].fillna("Unknown")

In [23]:
df_clean.isnull().sum()

company                   0
location                  0
total_laid_off         1528
date                      0
percentage_laid_off    1641
industry                  0
source                    3
stage                     5
funds_raised            512
country                   0
date_added                0
dtype: int64

In [24]:
df_clean[df_clean["source"].isna()]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
1606,Trellix,SF Bay Area,NaN,7/7/2023,NaN,Security,NaN,Unknown,35.0,United States,7/11/2023
2583,N-able Technologies,Raleigh,NaN,12/9/2022,NaN,Other,NaN,Post-IPO,225.0,United States,12/9/2022
3271,Tapas Media,SF Bay Area,NaN,7/28/2022,NaN,Media,NaN,Acquired,17.0,United States,8/2/2022

In [25]:
df_clean[df_clean["stage"].isna()]

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
2285,Soundwide,"Berlin, Non-U.S.",NaN,1/27/2023,0.08,Other,https://cdm.link/2023/01/soundwide-layoffs/,NaN,NaN,Germany,5/1/2023
2896,Advata,Seattle,32.0,10/28/2022,0.21,Healthcare,https://www.geekwire.com/2022/seattle-area-hea...,NaN,NaN,United States,10/31/2022
2902,Spreetail,Austin,NaN,10/27/2022,NaN,Retail,https://www.wearespreetail.com/blog/a-message-...,NaN,NaN,United States,10/28/2022
3251,Gatherly,Atlanta,NaN,7/31/2022,0.50,Marketing,Company exec,NaN,NaN,United States,8/2/2022
3634,Zapp,"London, Non-U.S.",NaN,5/25/2022,0.10,Food,https://sifted.eu/articles/zapp-layoffs-staff/,NaN,300.0,United Kingdom,5/27/2022

In [26]:
df_clean["source"] = df_clean["source"].fillna("Unknown")

In [27]:
df_clean["stage"] = df_clean["stage"].fillna("Unknown")

In [28]:
df_clean.isnull().sum()

company                   0
location                  0
total_laid_off         1528
date                      0
percentage_laid_off    1641
industry                  0
source                    0
stage                     0
funds_raised            512
country                   0
date_added                0
dtype: int64

In [29]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 4428 entries, 0 to 4427
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4428 non-null   str
 1   location             4428 non-null   str
 2   total_laid_off       2900 non-null   float64
 3   date                 4428 non-null   str
 4   percentage_laid_off  2787 non-null   float64
 5   industry             4428 non-null   str
 6   source               4428 non-null   str
 7   stage                4428 non-null   str
 8   funds_raised         3916 non-null   float64
 9   country              4428 non-null   str
 10  date_added           4428 non-null   str
dtypes: float64(3), str(8)
memory usage: 380.7 KB

In [30]:
df_clean["date"] = pd.to_datetime(df_clean["date"])

In [31]:
df_clean["date_added"] = pd.to_datetime(df_clean["date_added"])

In [32]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 4428 entries, 0 to 4427
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4428 non-null   str
 1   location             4428 non-null   str
 2   total_laid_off       2900 non-null   float64
 3   date                 4428 non-null   datetime64[us]
 4   percentage_laid_off  2787 non-null   float64
 5   industry             4428 non-null   str
 6   source               4428 non-null   str
 7   stage                4428 non-null   str
 8   funds_raised         3916 non-null   float64
 9   country              4428 non-null   str
 10  date_added           4428 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(3), str(6)
memory usage: 380.7 KB

In [33]:
df_clean["year"] = df_clean["date"].dt.year

df_clean["month"] = df_clean["date"].dt.month

df_clean["month_name"] = df_clean["date"].dt.month_name()

df_clean["quarter"] = df_clean["date"].dt.quarter

In [34]:
df_clean[["date","year","month","month_name","quarter"]].head()

        date  year  month month_name  quarter
0 2026-05-29  2026      5        May        2
1 2026-05-28  2026      5        May        2
2 2026-05-27  2026      5        May        2
3 2026-05-27  2026      5        May        2
4 2026-05-27  2026      5        May        2

In [35]:
df_clean.to_csv(
    "../data/processed/layoffs_cleaned.csv",
    index=False
)